using System.Text.Json;
using System.Text.Json.Serialization;
using SonnetDB.Contracts;
using SonnetDB.Copilot;
using SonnetDB.Mcp;
using SonnetDB.Model;

namespace SonnetDB.Json;

/// <summary>
/// AOT-friendly <see cref="System.Text.Json"/> source-gen context。
/// 所有走 HTTP API 的请求 / 响应类型都必须出现在这里，
/// 保证 Native AOT publish 时不依赖反射。
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(SqlRequest))]
[JsonSerializable(typeof(SqlBatchRequest))]
[JsonSerializable(typeof(JsonElementValue))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, JsonElementValue>))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(ResultMeta))]
[JsonSerializable(typeof(ResultEnd))]
[JsonSerializable(typeof(GeoPoint))]
[JsonSerializable(typeof(CreateDatabaseRequest))]
[JsonSerializable(typeof(DatabaseOperationResponse))]
[JsonSerializable(typeof(DatabaseListResponse))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(SetupStatusResponse))]
[JsonSerializable(typeof(SetupInitializeRequest))]
[JsonSerializable(typeof(SetupInitializeResponse))]
[JsonSerializable(typeof(BulkIngestResponse))]
[JsonSerializable(typeof(KvGetRequest))]
[JsonSerializable(typeof(KvSetRequest))]
[JsonSerializable(typeof(KvDeleteRequest))]
[JsonSerializable(typeof(KvGetManyRequest))]
[JsonSerializable(typeof(KvSetManyRequest))]
[JsonSerializable(typeof(KvSetManyEntry))]
[JsonSerializable(typeof(KvDeleteManyRequest))]
[JsonSerializable(typeof(KvPrefixRequest))]
[JsonSerializable(typeof(KvCleanExpiredRequest))]
[JsonSerializable(typeof(KvIncrementRequest))]
[JsonSerializable(typeof(KvCasRequest))]
[JsonSerializable(typeof(KvExpireRequest))]
[JsonSerializable(typeof(KvEntryResponse))]
[JsonSerializable(typeof(KvValueResponse))]
[JsonSerializable(typeof(KvGetManyResponse))]
[JsonSerializable(typeof(KvValueItemResponse))]
[JsonSerializable(typeof(KvSetResponse))]
[JsonSerializable(typeof(KvSetManyResponse))]
[JsonSerializable(typeof(KvDeleteResponse))]
[JsonSerializable(typeof(KvIncrementResponse))]
[JsonSerializable(typeof(KvCasResponse))]
[JsonSerializable(typeof(KvBooleanResponse))]
[JsonSerializable(typeof(KvTtlResponse))]
[JsonSerializable(typeof(KvScanResponse))]
[JsonSerializable(typeof(KvStatsResponse))]
[JsonSerializable(typeof(DocumentCollectionCreateRequest))]
[JsonSerializable(typeof(DocumentCollectionOperationResponse))]
[JsonSerializable(typeof(DocumentValidatorContract))]
[JsonSerializable(typeof(DocumentValidatorRuleContract))]
[JsonSerializable(typeof(DocumentValidatorResponse))]
[JsonSerializable(typeof(DocumentWriteItem))]
[JsonSerializable(typeof(DocumentInsertManyRequest))]
[JsonSerializable(typeof(DocumentFindRequest))]
[JsonSerializable(typeof(DocumentFilterContract))]
[JsonSerializable(typeof(DocumentProjectionContract))]
[JsonSerializable(typeof(DocumentSortContract))]
[JsonSerializable(typeof(DocumentItemResponse))]
[JsonSerializable(typeof(DocumentFindResponse))]
[JsonSerializable(typeof(DocumentFindOneResponse))]
[JsonSerializable(typeof(DocumentUpdateContract))]
[JsonSerializable(typeof(DocumentUpdateOneRequest))]
[JsonSerializable(typeof(DocumentUpdateManyRequest))]
[JsonSerializable(typeof(DocumentDeleteOneRequest))]
[JsonSerializable(typeof(DocumentDeleteManyRequest))]
[JsonSerializable(typeof(DocumentWriteErrorResponse))]
[JsonSerializable(typeof(DocumentWriteResponse))]
[JsonSerializable(typeof(DocumentCountRequest))]
[JsonSerializable(typeof(DocumentCountResponse))]
[JsonSerializable(typeof(DocumentDistinctRequest))]
[JsonSerializable(typeof(DocumentDistinctResponse))]
[JsonSerializable(typeof(DocumentAggregateRequest))]
[JsonSerializable(typeof(DocumentAggregateStageContract))]
[JsonSerializable(typeof(DocumentAggregateGroupContract))]
[JsonSerializable(typeof(DocumentAggregateGroupKeyContract))]
[JsonSerializable(typeof(DocumentAggregateAccumulatorContract))]
[JsonSerializable(typeof(DocumentAggregateUnwindContract))]
[JsonSerializable(typeof(DocumentAggregateDistinctContract))]
[JsonSerializable(typeof(DocumentAggregateResponse))]
[JsonSerializable(typeof(List<DocumentWriteItem>))]
[JsonSerializable(typeof(List<DocumentWriteErrorResponse>))]
[JsonSerializable(typeof(List<DocumentItemResponse>))]
[JsonSerializable(typeof(List<DocumentFilterContract>))]
[JsonSerializable(typeof(List<DocumentProjectionContract>))]
[JsonSerializable(typeof(List<DocumentSortContract>))]
[JsonSerializable(typeof(List<DocumentValidatorRuleContract>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<DocumentAggregateStageContract>))]
[JsonSerializable(typeof(List<DocumentAggregateGroupKeyContract>))]
[JsonSerializable(typeof(List<DocumentAggregateAccumulatorContract>))]
[JsonSerializable(typeof(List<JsonElement>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, JsonElement>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(MqPublishRequest))]
[JsonSerializable(typeof(MqPublishResponse))]
[JsonSerializable(typeof(MqPublishBatchEntry))]
[JsonSerializable(typeof(MqPublishBatchRequest))]
[JsonSerializable(typeof(MqPublishBatchResponse))]
[JsonSerializable(typeof(List<MqPublishBatchEntry>))]
[JsonSerializable(typeof(List<long>))]
[JsonSerializable(typeof(MqPullRequest))]
[JsonSerializable(typeof(MqMessageResponse))]
[JsonSerializable(typeof(MqPullResponse))]
[JsonSerializable(typeof(MqAckRequest))]
[JsonSerializable(typeof(MqAckResponse))]
[JsonSerializable(typeof(MqStatsResponse))]
[JsonSerializable(typeof(List<MqMessageResponse>))]
// ---- M29 A #245 多模型只读管理契约 ----
[JsonSerializable(typeof(KvKeyspaceListResponse))]
[JsonSerializable(typeof(KvScanCursorRequest))]
[JsonSerializable(typeof(KvScanCursorResponse))]
[JsonSerializable(typeof(VectorIndexStatResponse))]
[JsonSerializable(typeof(VectorIndexStat))]
[JsonSerializable(typeof(List<VectorIndexStat>))]
[JsonSerializable(typeof(VectorSearchPreviewRequest))]
[JsonSerializable(typeof(VectorSearchPreviewResponse))]
[JsonSerializable(typeof(VectorSearchPreviewHit))]
[JsonSerializable(typeof(List<VectorSearchPreviewHit>))]
[JsonSerializable(typeof(FullTextIndexStatResponse))]
[JsonSerializable(typeof(FullTextIndexStat))]
[JsonSerializable(typeof(List<FullTextIndexStat>))]
[JsonSerializable(typeof(FullTextSearchPreviewRequest))]
[JsonSerializable(typeof(FullTextSearchPreviewResponse))]
[JsonSerializable(typeof(FullTextSearchPreviewHit))]
[JsonSerializable(typeof(List<FullTextSearchPreviewHit>))]
[JsonSerializable(typeof(FullTextAnalyzeRequest))]
[JsonSerializable(typeof(FullTextAnalyzeResponse))]
[JsonSerializable(typeof(FullTextTokenInfo))]
[JsonSerializable(typeof(List<FullTextTokenInfo>))]
[JsonSerializable(typeof(MqTopicListResponse))]
[JsonSerializable(typeof(MqTopicInfo))]
[JsonSerializable(typeof(List<MqTopicInfo>))]
[JsonSerializable(typeof(MqOffsetsResponse))]
[JsonSerializable(typeof(MqConsumerLag))]
[JsonSerializable(typeof(List<MqConsumerLag>))]
[JsonSerializable(typeof(MqBrowseRequest))]
[JsonSerializable(typeof(MqBrowseResponse))]
[JsonSerializable(typeof(ObjectBucketCreateRequest))]
[JsonSerializable(typeof(ObjectBucketResponse))]
[JsonSerializable(typeof(ObjectBucketResponse[]))]
[JsonSerializable(typeof(ObjectInfoResponse))]
[JsonSerializable(typeof(ObjectListResponse))]
[JsonSerializable(typeof(ObjectDeleteManyRequest))]
[JsonSerializable(typeof(ObjectDeleteResultResponse))]
[JsonSerializable(typeof(ObjectDeleteManyResponse))]
[JsonSerializable(typeof(ObjectVersionListResponse))]
[JsonSerializable(typeof(ObjectInfoResponse[]))]
[JsonSerializable(typeof(ObjectCopyResponse))]
[JsonSerializable(typeof(ObjectTagsRequest))]
[JsonSerializable(typeof(MultipartUploadCreateRequest))]
[JsonSerializable(typeof(MultipartUploadCreateResponse))]
[JsonSerializable(typeof(MultipartPartResponse))]
[JsonSerializable(typeof(MultipartCompleteRequest))]
[JsonSerializable(typeof(PresignedObjectUrlCreateRequest))]
[JsonSerializable(typeof(PresignedObjectUrlResponse))]
[JsonSerializable(typeof(ObjectLifecycleRequest))]
[JsonSerializable(typeof(ObjectLifecycleResponse))]
[JsonSerializable(typeof(ObjectLifecycleApplyResponse))]
[JsonSerializable(typeof(ObjectAuditEntryResponse))]
[JsonSerializable(typeof(ObjectAuditListResponse))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(List<KvSetManyEntry>))]
[JsonSerializable(typeof(List<KvEntryResponse>))]
[JsonSerializable(typeof(List<KvValueItemResponse>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, long>))]
[JsonSerializable(typeof(MetricsSnapshotEvent))]
[JsonSerializable(typeof(SlowQueryEvent))]
[JsonSerializable(typeof(DatabaseEvent))]
[JsonSerializable(typeof(McpDatabaseStatsResult))]
[JsonSerializable(typeof(McpDatabaseListResult))]
[JsonSerializable(typeof(McpMeasurementColumnResult))]
[JsonSerializable(typeof(McpMeasurementListResult))]
[JsonSerializable(typeof(McpMeasurementSchemaResult))]
[JsonSerializable(typeof(McpSqlQueryResult))]
[JsonSerializable(typeof(McpSampleRowsResult))]
[JsonSerializable(typeof(McpExplainSqlResult))]
[JsonSerializable(typeof(McpDraftSqlResult))]
[JsonSerializable(typeof(McpExecuteSqlResult))]
[JsonSerializable(typeof(McpDocsSearchHit))]
[JsonSerializable(typeof(McpDocsSearchResult))]
[JsonSerializable(typeof(McpSkillSearchHit))]
[JsonSerializable(typeof(McpSkillSearchResult))]
[JsonSerializable(typeof(McpSkillLoadResult))]
// ---- Schema API ----
[JsonSerializable(typeof(SchemaResponse))]
[JsonSerializable(typeof(MeasurementInfo))]
[JsonSerializable(typeof(ColumnInfo))]
[JsonSerializable(typeof(VectorIndexInfo))]
[JsonSerializable(typeof(KeyValueInfo))]
[JsonSerializable(typeof(TableInfo))]
[JsonSerializable(typeof(TableColumnInfo))]
[JsonSerializable(typeof(TableIndexInfo))]
[JsonSerializable(typeof(DocumentCollectionInfo))]
[JsonSerializable(typeof(DocumentJsonIndexInfo))]
[JsonSerializable(typeof(DocumentFullTextIndexInfo))]
[JsonSerializable(typeof(IndexLifecycleInfo))]
[JsonSerializable(typeof(BackupStatusInfo))]
[JsonSerializable(typeof(MaintenanceRequest))]
[JsonSerializable(typeof(MaintenanceResponse))]
[JsonSerializable(typeof(MaintenanceCheckInfo))]
[JsonSerializable(typeof(BackupVerificationInfo))]
[JsonSerializable(typeof(RestoreDryRunInfo))]
[JsonSerializable(typeof(IndexMaintenanceInfo))]
[JsonSerializable(typeof(QualityAnalysisInfo))]
[JsonSerializable(typeof(QualityIndexInfo))]
[JsonSerializable(typeof(List<MeasurementInfo>))]
[JsonSerializable(typeof(List<ColumnInfo>))]
[JsonSerializable(typeof(List<VectorIndexInfo>))]
[JsonSerializable(typeof(List<KeyValueInfo>))]
[JsonSerializable(typeof(List<TableInfo>))]
[JsonSerializable(typeof(List<TableColumnInfo>))]
[JsonSerializable(typeof(List<TableIndexInfo>))]
[JsonSerializable(typeof(List<DocumentCollectionInfo>))]
[JsonSerializable(typeof(List<DocumentJsonIndexInfo>))]
[JsonSerializable(typeof(List<DocumentFullTextIndexInfo>))]
[JsonSerializable(typeof(List<IndexLifecycleInfo>))]
[JsonSerializable(typeof(List<MaintenanceCheckInfo>))]
[JsonSerializable(typeof(List<QualityIndexInfo>))]
[JsonSerializable(typeof(List<string>))]
// ---- AI 公开 API ----
[JsonSerializable(typeof(AiConfigResponse))]
[JsonSerializable(typeof(AiConfigRequest))]
[JsonSerializable(typeof(AiCloudDeviceCodeRequest))]
[JsonSerializable(typeof(AiCloudDeviceCodeResponse))]
[JsonSerializable(typeof(AiCloudDeviceTokenRequest))]
[JsonSerializable(typeof(AiCloudDeviceTokenResponse))]
[JsonSerializable(typeof(AiCloudModelsResponse))]
[JsonSerializable(typeof(AiChatRequest))]
[JsonSerializable(typeof(AiMessage))]
[JsonSerializable(typeof(AiStatusResponse))]
[JsonSerializable(typeof(List<AiMessage>))]
// ---- AI SSE 内部事件 ----
[JsonSerializable(typeof(SseTokenEvent))]
[JsonSerializable(typeof(SseErrorEvent))]
// ---- OpenAI-compatible 代理内部协议 ----
[JsonSerializable(typeof(OpenAiRequest))]
[JsonSerializable(typeof(OpenAiChunk))]
[JsonSerializable(typeof(OpenAiChoice))]
[JsonSerializable(typeof(OpenAiDelta))]
[JsonSerializable(typeof(List<OpenAiChoice>))]
// ---- Copilot OpenAI-compatible 内部协议 ----
[JsonSerializable(typeof(OpenAiEmbeddingRequest))]
[JsonSerializable(typeof(OpenAiEmbeddingResponse))]
[JsonSerializable(typeof(OpenAiEmbeddingItem))]
[JsonSerializable(typeof(OpenAiChatCompletionRequest))]
[JsonSerializable(typeof(OpenAiChatCompletionResponse))]
[JsonSerializable(typeof(OpenAiChatCompletionChoice))]
[JsonSerializable(typeof(OpenAiChatCompletionMessage))]
[JsonSerializable(typeof(OpenAiModelsResponse))]
[JsonSerializable(typeof(OpenAiModelItem))]
// ---- Copilot 公开 API（PR #64）----
[JsonSerializable(typeof(CopilotIngestRequest))]
[JsonSerializable(typeof(CopilotIngestResponse))]
[JsonSerializable(typeof(CopilotSearchRequest))]
[JsonSerializable(typeof(CopilotSearchResponse))]
[JsonSerializable(typeof(CopilotSearchHit))]
[JsonSerializable(typeof(List<CopilotSearchHit>))]
// ---- Copilot 技能库 API（PR #65）----
[JsonSerializable(typeof(CopilotSkillsIngestRequest))]
[JsonSerializable(typeof(CopilotSkillsIngestResponse))]
[JsonSerializable(typeof(CopilotSkillsSearchRequest))]
[JsonSerializable(typeof(CopilotSkillsSearchResponse))]
[JsonSerializable(typeof(CopilotSkillsSearchHit))]
[JsonSerializable(typeof(List<CopilotSkillsSearchHit>))]
[JsonSerializable(typeof(CopilotSkillLoadResponse))]
[JsonSerializable(typeof(CopilotSkillsListResponse))]
[JsonSerializable(typeof(CopilotKnowledgeStatusResponse))]
[JsonSerializable(typeof(CopilotChatRequest))]
[JsonSerializable(typeof(CopilotChatEvent))]
[JsonSerializable(typeof(CopilotCitation))]
[JsonSerializable(typeof(List<CopilotCitation>))]
// ---- Cloud Copilot Runtime 协议 ----
[JsonSerializable(typeof(CopilotCloudChatRequest))]
[JsonSerializable(typeof(CopilotCloudDatabaseContext))]
[JsonSerializable(typeof(CopilotCloudClientContext))]
[JsonSerializable(typeof(CopilotCloudContextSummary))]
[JsonSerializable(typeof(CopilotCloudMeasurementSummary))]
[JsonSerializable(typeof(CopilotCloudFieldSummary))]
[JsonSerializable(typeof(CopilotCloudContextLimits))]
[JsonSerializable(typeof(CopilotCloudRuntimeEvent))]
[JsonSerializable(typeof(CopilotCloudToolCallEvent))]
[JsonSerializable(typeof(CopilotCloudToolResultEvent))]
[JsonSerializable(typeof(CopilotCloudRiskReview))]
[JsonSerializable(typeof(CopilotCloudPromptReference))]
[JsonSerializable(typeof(CopilotCloudKnowledgeReference))]
[JsonSerializable(typeof(CopilotCloudToolResultRequest))]
[JsonSerializable(typeof(CopilotCloudToolResultPayload))]
[JsonSerializable(typeof(CopilotCloudToolResultResponse))]
// ---- Copilot Agent 内部协议（PR #67）----
[JsonSerializable(typeof(CopilotToolPlan))]
[JsonSerializable(typeof(CopilotPlannedTool))]
internal sealed partial class ServerJsonContext : JsonSerializerContext;
